### ISSUE TITLE
TASK:build responsiveness into the search bar and make sure it serves text when queried

### ISSUE THREAD

**Issue by breadethewbaker** [cse442-fall-2019-offering/442projects-chrome-extenders#20]

**Comment by sarrasou** [comment]
Acceptance test:
1. Click on extension icon
2. A new window should pop up
3. Type a word into the search bar and press enter
4. The word repeated should show up underneath the search bar.
5. Close window

**Comment by sarrasou** [comment]
Acceptance test passed
