### ISSUE TITLE
TASK: communicate with oxford dictionary API to pull desired information

### ISSUE THREAD

**Issue by vbaziuk** [cse442-fall-2019-offering/442projects-chrome-extenders#22]
As a user, I want to be able to retrieve definitions quickly from a reliable source

**Comment by sarrasou** [comment]
Unit tests created to:

Get definitions of input words from Oxford Dictionary api
Get synonyms of input words from Oxford Dictionary api
Get antonym of input words from Oxford Dictionary api
Get examples of input word used in a sentence from Oxford Dictionary api
Get all requests in a single data structure
Send request to project API

**Comment by sarrasou** [comment]
All unit tests passed.
Unit tests located in unit-tests.py
