### ISSUE TITLE
TASK: Host the website on server

### ISSUE THREAD

**Issue by PriyankaDhakite** [cse442-fall-2019-offering/442projects-chrome-extenders#24]
As a user, I would like to have a steady URL to access a one-stop website for the extension.

**Comment by sarrasou** [comment]
https://www-student.cse.buffalo.edu/CSE442-542/2019-Fall/cse-442c/442projects-chrome-extenders/ext-web-ui/src/app/app.component.html

**Comment by sarrasou** [comment]
Acceptance test:
1. Click link above
2. View extension website with logo, description, and link to GitHub from any computer or browser.
3. Close tab.

**Comment by sarrasou** [comment]
Acceptance test passed.
