### ISSUE TITLE
BUGFIX: search ui resets when a new word is entered

### ISSUE THREAD

**Issue by breadethewbaker** [cse442-fall-2019-offering/442projects-chrome-extenders#39]
Currently, ui maintains a history of definitions and synonyms for the previous words entered

**Comment by sarrasou** [comment]
Acceptance test:
1. Open extension
2. Type word into search bar (i.e. word) and press enter
3. See definition and synonym
4. backspace and type another word into search bar (i.e. sound) and press enter
5. See definition and synonym of new word
6. Close extension window

**Comment by sarrasou** [comment]
Acceptance test passed
