### ISSUE TITLE
BUGFIX: error message when word not found

### ISSUE THREAD

**Issue by breadethewbaker** [cse442-fall-2019-offering/442projects-chrome-extenders#40]
Currently, the ui is not responsive when word isn't found

**Comment by sarrasou** [comment]
1. Open extension window
2. Type random gibberish into searchbox (i.e bfuwbfjdsbdns) and press enter
3. See error message
4. Type real word into search box and press enter
5. See definition and synonym
6. Close extension window

**Comment by breadethewbaker** [comment]
Acceptance Test Passed
